#!/usr/bin/env python
template = open("ToolTemplate.java").read()

import sys
#tooltype = sys.argv[1].capitalize()
undername = sys.argv[1]
tooltype = undername.split("_")[-1].capitalize()
camelname = "".join([i.capitalize() for i in undername.split("_")])
camelname_low = camelname[0].lower() + camelname[1:]

things = {
        "TOOLTYPE": tooltype,
        "CAMELCASE_NAME": camelname,
        "CAMELCASE_NAME_LOWER": camelname_low,
        "UNDERSCORED_NAME": undername
}

for i in things:
    template = template.replace(i, things[i])

f = open("%s.java" % camelname, "w")
f.write(template)
f.close()
